### PR TITLE
feat: pass the event object to the component action

### PR DESCRIPTION
**Pull request by ncoden**
Changes:
- pass the event object to the component action
- update README

poke @zeppelin

### CODE REVIEW

**Comment by zeppelin** [comment]
@ncoden Hey, thanks for the contrib & the poke! :)

Looks like Travis is failing though

**Comment by ncoden** [comment]
I'll check

**Comment by ncoden** [comment]
@zeppelin I don't know `ember-qunit` enough to fix this. I think the `didClickOutside` handler received the click event but expected nothing. I don't know how to bypass that.

**Comment by zeppelin** [comment]
@ncoden I'll take a look at it tomorrow.

**Comment by zeppelin** [comment]
Closing in favor of #20

**Pull request closed without merging**
