### PR TITLE
Upgrade ember-modifier to 2.1.0

### PR DESCRIPTION
**Pull request by lukemelia**

### CODE REVIEW

**Comment by lukemelia** [comment]
Note that this is required for ember-click-outside to be compatible with Ember 3.20+

**Comment by gilest** [comment]
This would be great 🙌

**Comment by zeppelin** [comment]
Ah, GH notifications be like...

Thanks Luke, I’ll merge it once I got home!

**Comment by gilest** [comment]
I've tested this in my project with `^2.1.1` pinned via yarn resolutions. Seems to work fine

**Comment by zeppelin** [comment]
Released as `2.0.0` 🎉, thank you all for your patience! ❤️

**Pull request merged**
