### PR TITLE
Event type flexibility

### PR DESCRIPTION
**Pull request by crowjonah**
The app I work on is currently using a fork of the mixin that allows for flexibility in the event to which the listener is bound (and removed). This is especially handy when something like a modal or popup is overlapping a large amount of an interactive element (in our case a map, where clicking and dragging pans across it).

I've just picked up the modifier work here in anticipation of the deprecation of mixins (https://github.com/emberjs/rfcs/pull/528), and extended the event flexibility to this implementation.

I think this may also solve https://github.com/zeppelin/ember-click-outside/issues/48, and relates to https://github.com/zeppelin/ember-click-outside/issues/49

Note: dependencies haven't changed, but I did need to regenerate the lockfile in order to get tests to pass in the current state of your branch.

### CODE REVIEW

**Comment by zeppelin** [comment]
Hey, that's really cool! I'll look into it more thoroughly tomorrow, but looks like an easy merge :)

**Comment by zeppelin** [comment]
I'll investigate why tests are suddenly failing, then merge right after

**Comment by crowjonah** [comment]
> I'll investigate why tests are suddenly failing, then merge right after

Yeah, I looked briefly at the master branch and it looks like some of the latest and greatest modifier stuff might preclude earlier versions of ember and/or node. I see you have the modifier manager polyfill, though, so I'm not sure what the culprit could be.

**Comment by crowjonah** [comment]
I've merged the lastest from `master` here!

**Comment by zeppelin** [comment]
@crowjonah Released as `v1.2.0` 🎉 

Thanks for the GREAT contribution!!

**Pull request merged**
