### PR TITLE
Apply cursor:pointer only to body on iOS (using browser detection)

### PR DESCRIPTION
**Pull request by FelixAkk**

### CODE REVIEW

**Comment by zeppelin** [comment]
First: amazing work!
Second: so long we only detect iOS, is the whole 600+ lines of 	browser detect package is really necessary to filter to a single browser? :)

**Comment by zeppelin** [comment]
I think we should rather take the chance of an unlikely breaking UA change in iOS, than including a library of which we only use like 3%. (And we don't have the ability to tree-shake the rest)

I still didn't have the time to properly test it on iOS devices, tho :/

**Comment by FelixAkk** [comment]
Which method of iOS detection would you prefer in that case? This is rather debated due to the many quirks there are, like Microsoft making IE11 identify as iPhone like to fool Gmail. The method in the bowser package doesn't really seem a simple line that we can copy paste unfortunately

**Comment by FelixAkk** [comment]
@zeppelin I updated the PR to use an inline iOS detection. From my limited understanding this isn't watertight but pretty robust nonetheless

**Comment by FelixAkk** [comment]
@zeppelin do you perhaps have an hour this week to look into the PR? :) I implemented iOS detection in the mixin code now. Testing with Firefox/Chrome and the iPhone simulator from Xcode shows this should work.

**Comment by zeppelin** [comment]
Looks OK! Will merge & release tomorrow from my computer!

**Comment by zeppelin** [comment]
Released as `v1.0.0`. 🎉

@FelixAkk Thank you for the excellent work, I only held back the `1.0.0` release because of this! :)

**Comment by FelixAkk** [comment]
@zeppelin Thanks a lot! :) Happy to contribute!

**Comment by FelixAkk** [comment]
@zeppelin oh wow, congratulations! 😄 I hope he's doing great. Can very well understand the distraction ;)

**Pull request merged**
