### PR TITLE
Rename "action" handler to "onClickOutside"

### PR DESCRIPTION
**Pull request by AndreJoaquim**
Closes https://github.com/zeppelin/ember-click-outside/issues/45.

I've decided to supersede `onClickOutside`. This means that if `onClickOutside` is passed, `action` is ignored. If both are passed, only `onClickOutside` is called. If only `action` is passed, only `action` is called. 

I've added two deprecation warnings:
1. When both `onClickOutside` and `action` handlers are passed and are functions, it warns that only `onClickOutside` should be defined
2. When only `action` handler is passed, it warns that it's deprecated and `onClickOutside` should be used instead

I've added and adapted the test suite to include the new behaviours, as well as adapting the README.md

### CODE REVIEW

**Comment by zeppelin** [comment]
Great work, almost clicked the merge button! :) But then it hit me if you could camelcase `except-selector` (`exceptSelector`) as well? It'd be nice to remain consistent with the casing of the `onClickOutside` argument.

**Comment by AndreJoaquim** [comment]
@Zeppelin Totally agree! Will do that today :)

**Comment by AndreJoaquim** [comment]
@zeppelin Sorry, I've not yet managed to pick it up, but it's nor forgotten!

**Comment by zeppelin** [comment]
@AndreJoaquim no worries, we're not in a hurry ;)

**Comment by ondrejsevcik** [comment]
hey guys, did you consider using `deprecatingAlias` for this? https://api.emberjs.com/ember/3.9/functions/@ember%2Fobject%2Fcomputed/deprecatingAlias

I think it may serve its purpose in this case.

**Comment by zeppelin** [comment]
@AndreJoaquim I've deprecated `except-selector` in favor of `exceptSelector`, also removed the `action`<`onClickOutside` precedence, because `deprecatingAlias` (thanks, @ondrejsevcik!) does not allow to have that. In exchange, we have a deprecation workflow more aligned with the rest of the ecosystem.

Thank you for the great contribution!

Next up: element modifiers :)

**Comment by AndreJoaquim** [comment]
@zeppelin Cool!

**Pull request merged**
