### PR TITLE
Update to latest Ember CLI (including HTMLBars)

### PR DESCRIPTION
**Pull request by zeppelin**

### CODE REVIEW

**Comment by zeppelin** [comment]
@osxi @JoshSmith @leizhao4 released `0.1.0`, thank you guys for your patience!

**Comment by JoshSmith** [comment]
Thank you @zeppelin!

**Comment by zeppelin** [comment]
@JoshSmith sorry it took this long. I've also released `v0.1.2` with the event listener bugfix

**Comment by JoshSmith** [comment]
@zeppelin no need to apologize! Ecstatic to see the progress.

**Pull request merged**
