### PR TITLE
Remove Duplicate ember-cli-htmlbars

### PR DESCRIPTION
**Pull request by osxi**

### CODE REVIEW

**Comment by osxi** [comment]
Let's hold off on this for now. I'm investigating some crazy dependency issues.

**Comment by zeppelin** [comment]
Thanks. Let me know when it's ready.

**Comment by osxi** [comment]
@zeppelin It's ready! I'll upgrade ember-cli later so we can boost the Ember Observer score again.

**Comment by osxi** [comment]
https://github.com/zeppelin/ember-click-outside/pull/17 makes this PR unnecessary.

**Pull request closed without merging**
